name: NeoCoreTest

on:
  pull_request:
    branches: [master]
    types: [synchronize, opened, reopened, ready_for_review]

  # run checks on any change of master, including merge of PRs
  push:
    branches: [master]

jobs:
  multi-os-python-numpy:
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: true
      matrix:
        os: ["ubuntu-latest", "windows-latest"]
        # "macos-latest",
        python-version: ['3.8', '3.9', '3.10', '3.11']
        numpy-version: ['1.19.5', '1.20.3', '1.21.6', '1.22.4', '1.23.5', '1.24.1']
        exclude:
           - python-version: '3.10'
             numpy-version: '1.19.5'
           - python-version: '3.10'
             numpy-version: '1.20.3'
           - python-version: '3.11'
             numpy-version: '1.19.5'
           - python-version: '3.11'
             numpy-version: '1.20.3'
           - python-version: '3.11'
             numpy-version: '1.21.6'
    steps:
        - name: Set up Python ${{ matrix.python-version }}
          uses: actions/setup-python@v4
          with:
            python-version: ${{ matrix.python-version }}

        - name: Checkout repository
          uses: actions/checkout@v3

        - name: Get changed files
          id: changed-files
          uses: tj-actions/changed-files@v35

        - name: Module changes
          id: modules-changed
          # check if core (or toml) has been changed.
          run: |
            for file in ${{ steps.changed-files.outputs.all_changed_files }}; do
              if [[ $file == *"/core/"* || $file == *"/pyproject.toml" ]]; then
                echo "Core changed"
                echo "CORE_CHANGED=true" >> $GITHUB_OUTPUT
              fi
            done

        - name: Core changed?
          run: echo "Core changed == ${{steps.modules-changed.outputs.CORE_CHANGED == 'true'}}"

        - name: Install numpy ${{ matrix.numpy-version }}
          if: ${{ steps.modules-changed.outputs.CORE_CHANGED == 'true' }}
          run: |
            python -m pip install --upgrade pip
            pip install numpy==${{ matrix.numpy-version }}
            pip install pytest pytest-cov
            pip install .

        - name: List pip packages
          if: ${{ steps.modules-changed.outputs.CORE_CHANGED == 'true' }}
          run: |
            pip -V
            pip list

        - name: Run tests
          if: ${{ steps.modules-changed.outputs.CORE_CHANGED == 'true' }}
          run: |
            pytest --cov=neo neo/test/coretest
