name: NeoIoTest-automatic-trigger

on:
  pull_request:
    branches: [master]
    types: [synchronize, opened, reopened, ready_for_review]

  # run checks on any change of master, including merge of PRs
  push:
    branches: [master]

jobs:
  call-iotests:
    uses: Neuralensemble/python-neo/.github/workflows/io-test.yml@main
    with:
      os: ubuntu-latest
